import java.util.*;

class Solution {
    public char findTheDifference(String s, String t) {

        int total = 0;
        for (int i = 0; i < t.length(); i++) {
            char ch = t.charAt(i);
            total = total + (int) ch;
        }
        for (int i = 0; i < s.length(); i++) {
            char ch = s.charAt(i);
            total = total - (int) ch;
        }

        char ans = (char) total;
        return ans;
    }

    public char findTheDifferenceII(String s, String t) {
        HashMap<Character,Integer> map = new HashMap<>();
        for (char c : t.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }

        // Decrease frequency using s
        for (char c : s.toCharArray()) {
            map.put(c, map.get(c) - 1);
        }

        // Find the extra character
        for (char c : map.keySet()) {
            if (map.get(c) > 0) {
                return c;
            }
        }
        return ' ';
    }
}

public class Q20_Find_diffrence {
    public static void main(String[] args) {
        /*
         * 389. Find the Difference
           https://leetcode.com/problems/find-the-difference/description/
         * You are given two strings s and t.
         * 
         * String t is generated by random shuffling string s and then add one more
         * letter at a random position.
         * 
         * Return the letter that was added to t.
         * 
         * 
         * 
         * Example 1:
         * 
         * Input: s = "abcd", t = "abcde"
         * Output: "e"
         * Explanation: 'e' is the letter that was added.
         * Example 2:
         * 
         * Input: s = "", t = "y"
         * Output: "y"
         * 
         * 
         * Constraints:
         * 
         * 0 <= s.length <= 1000
         * t.length == s.length + 1
         * s and t consist of lowercase English letters.
         */
        Solution ans = new Solution();

        String s = "abcd";
        String t = "abcde";

        System.out.println(ans.findTheDifference(s, t));
        System.out.println(ans.findTheDifferenceII(s, t));
    }
}
